safe: true
markdown: kramdown
highlighter: rouge
permalink: /:title.html
relative_permalinks: false

default_theme: yandex2
default_width: 1024
default_ratio: 16x9
default_lang: en
default_body_class: list

author:
    name: Yours Truly
    # url:  http://example.com/
    company:
        name: Famous Inc.
        # url:  http://example.com/

fork_url: https://github.com/shower/shower
progress: true
line_numbers: true
